# Generated by Django 2.2 on 2020-02-09 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=121)),
                ('goal_id', models.IntegerField(default=0.0)),
                ('created_by', models.CharField(max_length=120)),
                ('moved_by', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=120)),
                ('goal_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='kolikay1989scrumy.GoalStatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=120)),
                ('created_by', models.CharField(max_length=120)),
                ('moved_from', models.CharField(max_length=120)),
                ('moved_to', models.CharField(max_length=120)),
                ('time_of_action', models.DateTimeField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kolikay1989scrumy.ScrumyGoals')),
            ],
        ),
    ]
