# Generated by Django 2.2 on 2020-02-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websocket', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateConnection',
            new_name='Connection',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.CharField(max_length=100),
        ),
    ]
